### ISSUE TITLE
some maps

### ISSUE THREAD

**Issue by Qixit** [MCResourcePile/overcast-maps-a-to-f#14]
Here are some of the maps that I've made/helped made. Not sure if any of these are up to date. Most of these are from when I copied the map repo before I stepped down... thats right suckas i have the map repo and i will use it to rebuild ocn to make myself a fortune out of minecraft pvp.

Adios.
[Artholis.zip](https://github.com/MCResourcePile/overcast-maps/files/784902/Artholis.zip)
[Lump.zip](https://github.com/MCResourcePile/overcast-maps/files/784903/Lump.zip)
[Gleon.zip](https://github.com/MCResourcePile/overcast-maps/files/784904/Gleon.zip)
[Neyud.zip](https://github.com/MCResourcePile/overcast-maps/files/784905/Neyud.zip)
[Kryta FFA.zip](https://github.com/MCResourcePile/overcast-maps/files/784906/Kryta.FFA.zip)
[Jyngli.zip](https://github.com/MCResourcePile/overcast-maps/files/784907/Jyngli.zip)

**Comment by Qixit** [comment]
oh was i meant to make a pull request?

**Comment by Qixit** [comment]
im sure mitchiii will do it for me

**Comment by Qixit** [comment]
@mitchiiii

**Comment by mitchts** [comment]
🐨🐨
